name: Package, Build, and Deploy to Amazon ECR

on:
  push:
    branches: ["master"]

env:
  AWS_REGION: us-east-1
  API_GATEWAY_ECR_REPOSITORY: ai-playlist/api-gateway
  LLM_SERVICE_ECR_REPOSITORY: ai-playlist/llm-service
  SERVICE_REGISTRY_ECR_REPOSITORY: ai-playlist/service-registry
  SOUNDCLOUD_SERVICE_ECR_REPOSITORY: ai-playlist/soundcloud-service
  SPOTIFY_SERVICE_ECR_REPOSITORY: ai-playlist/spotify-service

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Package Maven
        id: maven-package
        run: |
          echo "=== Packaging Maven ==="
          mvn package -DskipTests        

      - name: Maven Package, Docker Build, Docker Push
        id: package-build-push
        run: |
          services=(
            api-gateway
            llm-service
            service-registry
            spotify-service
            soundcloud-service
          )
          account_id="${{ secrets.ECR_ACCOUNT_ID }}"

          for service in "${services[@]}"; do
            echo "=== Building Maven Project: $service ==="

            IMAGE_NAME="ai-playlist/${service}"
            ECR_REPO="${account_id}.dkr.ecr.${AWS_REGION}.amazonaws.com/$IMAGE_NAME"

            echo "=== Building Docker Image: $IMAGE_NAME ==="
            docker build -t "$ECR_REPO:latest" "$service"

            echo "=== Pushing to ECR: $ECR_REPO ==="
            docker push "$ECR_REPO:latest"
          done